#!/usr/bin/env python
# coding: utf-8

# In[1]:


import sqlite3
from sqlite3 import Error


# fonction pour creer une base de donnees
def create_connection(db_name):
    """ fonction pour creer la base de donnees
    :param db_name: le nom de la base de donnees
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_name)
        return conn
    except Error as e:
        print(e)

    return conn


# fonction pour creer la table DIC
def create_table_db():
    conn = create_connection(r"dic-database.db")
    table_dic = """ CREATE TABLE IF NOT EXISTS DIC1 (
                                        id_ept integer ,
                                        nom text ,
                                        prenom text ,
                                        departement text,
                                        niveau text ,
                                        telephone text
                                    ); """
    try:
        c = conn.cursor()
        c.execute(table_dic)
    except Error as e:
        print(e)






# In[2]:



# fonction pour peupler la table DIC dans la base de donnees dic_database
def save_db(id_ele, nom_ele, prenom_el, departement_el, niveau_el, telephone_el):
    conn = create_connection(r"dic-database.db")
    donnees_ele = """ INSERT  INTO  DIC1(
                                        id_ept ,
                                        nom ,
                                        prenom ,
                                        departement ,
                                        niveau ,
                                        telephone
                                    )VALUES(
                                    ?,
                                    ? ,
                                    ? ,
                                    ? ,
                                    ? ,
                                    ? ) ; """
    c = conn.cursor()
    c.execute(donnees_ele , (id_ele, nom_ele, prenom_el, departement_el, niveau_el, telephone_el))
    conn.commit()
    return c.lastrowid


# In[6]:


# fonction pour supprimer un enregistrement
def delete_db(id_ele):
    conn = create_connection(r"dic-database.db")
    donnees_ele = """ DELETE FROM DIC1 WHERE id_ept = ? ; """

    c = conn.cursor()
    c.execute(donnees_ele, (id_ele, ))
    conn.commit()
    



# In[18]:


# fonction pour modifier un enregistrement
def get_all_db():
    conn = create_connection(r"dic-database.db")
  

    c = conn.cursor()
    c.execute("SELECT * FROM DIC1")
    
    lignes = c.fetchall()
    
    return dict(lignes)


# In[ ]:





# In[3]:


create_table_db()


# In[4]:



save_db(2, 'ndiaye', 'omar', 'git', 'DIC1', '785009876')


# In[5]:


save_db(1, 'ndiaye', 'Mamadou', 'git', 'DIC1', '785235415')


# In[7]:


delete_db(2)


# In[8]:


save_db(2, 'ndiaye', 'omar', 'git', 'DIC1', '785009876')


# In[10]:


modifier_db('DIOP' , 'DIARRA' , 'GIT' , 'DIC1' , '779765432' , 1)


# In[19]:


get_all_db()


# In[ ]:




